### ISSUE TITLE
Add styling to "How to Use" Starting Point Page

### ISSUE THREAD

**Issue by jaimiebutton** [thebuttonclan/pangolin#273] opened 2021-06-03 18:26 UTC
Apply global style to How To Use page using content from [Notion Page](https://www.notion.so/buttoninc/Getting-Started-ea106770cd754a02b22d07635fd3bafb).

**Comment by jlangy** [comment] 2021-06-09 20:37
I believe this is a duplicate of #289, closing it.

**Closed as completed by jlangy** 2021-06-09 20:37 UTC
